### ISSUE TITLE
Missing .gitmodules subsections?

### ISSUE THREAD

**Issue by ronaldmulero** [btopro/elmsln-developer#1]
Great stuff! Got this developer version up-and-running, too, and want to become waaaayyy more involved in the project.

Seems like .gitmodules is missing two subsections, though, no?:

```
diff --git a/.gitmodules b/.gitmodules
index 4c88fc1..14f3be6 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -13,3 +13,9 @@
 [submodule "elmsln-config-travis-ci"]
     path = instances/_development/config-travis-ci
     url = https://github.com/elmsln/elmsln-config-travis-ci.git
+[submodule "elmsln-logos"]
+    path = elmsln-logos
+    url = https://github.com/elmsln/elmsln-logos
+[submodule "elms-styles"]
+    path = elms-styles
+    url = https://github.com/elmsln/elms-styles
```

**Comment by btopro** [comment]
@ronaldmulero just saw this as I don't monitor this project actively :(. If your still interested in being actively involved we'd love to have you over in https://github.com/elmsln/elmsln/issues
